import { NameTable, type NameTableProps } from './NameTable';

const TEST_ENTRIES: Array<[string, NameTableProps]> = [
  [
    'default',
    {
      entries: [
        {
          id: 5461094,
          k: ['千尋'],
          r: ['かずひろ'],
          tr: [{ det: ['Kazuhiro'], type: ['given'] }],
          matchLen: 2,
        },
        {
          id: 5461095,
          k: ['千尋'],
          r: ['せんじん'],
          tr: [{ det: ['Senjin'], type: ['given'] }],
          matchLen: 2,
        },
        {
          id: 5461096,
          k: ['千尋'],
          r: ['ちず'],
          tr: [{ det: ['Chizu'], type: ['fem'] }],
          matchLen: 2,
        },
        {
          id: 5461097,
          k: ['千尋'],
          r: ['ちずる'],
          tr: [{ det: ['Chizuru'], type: ['fem'] }],
          matchLen: 2,
        },
        {
          id: 5461098,
          k: ['千尋'],
          r: ['ちづ'],
          tr: [{ det: ['Chizu'], type: ['fem'] }],
          matchLen: 2,
        },
        {
          id: 5461099,
          k: ['千尋'],
          r: ['ちづこ'],
          tr: [{ det: ['Chizuko'], type: ['fem'] }],
          matchLen: 2,
        },
        {
          id: 5461100,
          k: ['千尋'],
          r: ['ちなみ'],
          tr: [{ det: ['Chinami'], type: ['fem'] }],
          matchLen: 2,
        },
        {
          id: 5461101,
          k: ['千尋'],
          r: ['ちひろ'],
          tr: [{ det: ['Chihiro'], type: ['fem', 'surname'] }],
          matchLen: 2,
        },
        {
          id: 5459549,
          k: ['千'],
          r: ['う'],
          tr: [{ det: ['U'], type: ['surname'] }],
          matchLen: 1,
        },
        {
          id: 5459550,
          k: ['千'],
          r: ['せん'],
          tr: [{ det: ['Sen'], type: ['fem', 'surname'] }],
          matchLen: 1,
        },
        {
          id: 5459551,
          k: ['千'],
          r: ['せんざき'],
          tr: [{ det: ['Senzaki'], type: ['surname'] }],
          matchLen: 1,
        },
        {
          id: 5459552,
          k: ['千'],
          r: ['せんじ'],
          tr: [{ det: ['Senji'], type: ['unclass'] }],
          matchLen: 1,
        },
        {
          id: 5459553,
          k: ['千'],
          r: ['せんの'],
          tr: [{ det: ['Senno'], type: ['surname'] }],
          matchLen: 1,
        },
        {
          id: 5459554,
          k: ['千'],
          r: ['ち'],
          tr: [{ det: ['Chi'], type: ['surname'] }],
          matchLen: 1,
        },
        {
          id: 5459555,
          k: ['千'],
          r: ['ちたび'],
          tr: [{ det: ['Chitabi'], type: ['surname'] }],
          matchLen: 1,
        },
        {
          id: 5459556,
          k: ['千'],
          r: ['ちよん'],
          tr: [{ det: ['Chiyon'], type: ['surname'] }],
          matchLen: 1,
        },
        {
          id: 5459557,
          k: ['千'],
          r: ['ゆき'],
          tr: [{ det: ['Yuki'], type: ['fem'] }],
          matchLen: 1,
        },
      ],
      matchLen: 2,
      more: false,
      fxData: {
        currency: 'USD',
        rate: 0.006460990138464256,
        timestamp: 1732319104000,
      },
      preferredUnits: 'metric',
      copyState: { kind: 'inactive' },
    },
  ],

  [
    'few entries',
    {
      entries: [
        {
          id: 5461094,
          k: ['千尋'],
          r: ['かずひろ'],
          tr: [{ det: ['Kazuhiro'], type: ['given'] }],
          matchLen: 2,
        },
        {
          id: 5461095,
          k: ['千尋'],
          r: ['せんじん'],
          tr: [{ det: ['Senjin'], type: ['given'] }],
          matchLen: 2,
        },
        {
          id: 5461096,
          k: ['千尋'],
          r: ['ちず'],
          tr: [{ det: ['Chizu'], type: ['fem'] }],
          matchLen: 2,
        },
        {
          id: 5461097,
          k: ['千尋'],
          r: ['ちずる'],
          tr: [{ det: ['Chizuru'], type: ['fem'] }],
          matchLen: 2,
        },
      ],
      matchLen: 2,
      more: false,
      fxData: {
        currency: 'USD',
        rate: 0.006460990138464256,
        timestamp: 1732319104000,
      },
      preferredUnits: 'metric',
      copyState: { kind: 'inactive' },
    },
  ],
  [
    'multiple kanji entries',
    {
      entries: [
        {
          id: 5004039,
          r: ['ちひろ'],
          tr: [{ det: ['Chihiro'], type: ['fem'] }],
          matchLen: 3,
          k: [
            'ちひ緑',
            '愛洸',
            '茅尋',
            '茅祐',
            '今佑',
            '史尋',
            '千ひろ',
            '千絢',
            '千宇',
            '千栄',
            '千頴',
            '千央',
            '千嘉',
            '千雅',
            '千寛',
            '千京',
            '千空',
            '千啓',
            '千敬',
            '千景',
            '千絃',
            '千宏',
            '千弘',
            '千浩',
            '千彩',
            '千寿',
            '千潤',
            '千恕',
            '千泰',
            '千大',
            '千拓',
            '千宙',
            '千展',
            '千都',
            '千博',
            '千妃呂',
            '千妃路',
            '千妃露',
            '千比呂',
            '千比路',
            '千緋呂',
            '千飛路',
            '千姫',
            '千明',
            '千匁',
            '千弥',
            '千優',
            '千悠',
            '千祐',
            '千容',
            '千洋',
            '千陽',
            '千陽路',
            '千翼',
            '千礼',
            '千廣',
            '千洸',
            '千滉',
            '千皓',
            '千絋',
            '知央',
            '知寛',
            '知宏',
            '知弘',
            '知紘',
            '知尋',
            '知大',
            '知宙',
            '知博',
            '知比呂',
            '知優',
            '知裕',
            '知礼',
            '地寛',
            '地優',
            '智絢',
            '智嘉',
            '智寛',
            '智光',
            '智弘',
            '智寿',
            '智尋',
            '智大',
            '智優',
            '智裕',
            '智礼',
            '稚広',
            '稚尋',
            '稚裕',
            '秩弘',
            '名嘉眞',
          ],
        },
        {
          id: 5460121,
          k: [
            '千緩',
            '千凡',
            '千煕',
            '知広',
            '知寿',
            '知明',
            '知廣',
            '地大',
            '智広',
            '智比呂',
            '智弥',
            '智洋',
          ],
          r: ['ちひろ'],
          tr: [{ det: ['Chihiro'], type: ['unclass'] }],
          matchLen: 3,
        },
        {
          id: 5460409,
          k: ['千広', '千尋'],
          r: ['ちひろ'],
          tr: [{ det: ['Chihiro'], type: ['fem', 'surname'] }],
          matchLen: 3,
        },
        {
          id: 5460430,
          k: ['千紘', '千聖', '千裕'],
          r: ['ちひろ'],
          tr: [{ det: ['Chihiro'], type: ['masc', 'fem'] }],
          matchLen: 3,
        },
        {
          id: 5461013,
          k: ['千丈', '千比絽', '千仞', '千仭', '智央', '智宏', '智博'],
          r: ['ちひろ'],
          tr: [{ det: ['Chihiro'], type: ['given'] }],
          matchLen: 3,
        },
        {
          id: 5747016,
          k: ['千宗'],
          r: ['ちひろ'],
          tr: [{ det: ['Chihiro'], type: ['masc'] }],
          matchLen: 3,
        },
        {
          id: 5050301,
          r: ['チヒロ'],
          tr: [{ det: ['Chihiro'], type: ['fem'] }],
          matchLen: 3,
        },
        {
          id: 5510471,
          k: ['智姫'],
          r: ['ちひ'],
          tr: [{ det: ['Chihi'], type: ['fem'] }],
          matchLen: 2,
        },
        {
          id: 5307623,
          k: ['斎', '千', '地', '池', '遅', '陳吉', '楊'],
          r: ['ち'],
          tr: [{ det: ['Chi'], type: ['surname'] }],
          matchLen: 1,
        },
        {
          id: 5509454,
          k: ['智'],
          r: ['ち'],
          tr: [{ det: ['Chi'], type: ['surname', 'given'] }],
          matchLen: 1,
        },
        {
          id: 5049657,
          r: ['チ'],
          tr: [{ det: ['Chi'], type: ['unclass'] }],
          matchLen: 1,
        },
      ],
      matchLen: 3,
      more: false,
      fxData: {
        currency: 'USD',
        rate: 0.006460990138464256,
        timestamp: 1732319104000,
      },
      preferredUnits: 'metric',
      copyState: { kind: 'inactive' },
    },
  ],
  [
    'with meta',
    {
      entries: [
        {
          id: 5743402,
          k: ['６４'],
          r: ['ロクヨン'],
          tr: [{ det: ['Nintendo 64 (col)'], type: ['product'] }],
          matchLen: 2,
        },
      ],
      matchLen: 2,
      more: false,
      fxData: {
        currency: 'EUR',
        rate: 0.006201584078062961,
        timestamp: 1732319104000,
      },
      preferredUnits: 'metric',
      copyState: { kind: 'inactive' },
      meta: { type: 'currency', value: 64040, matchLen: 7 },
    },
  ],
  [
    'with meta (multicol)',
    {
      entries: [
        {
          id: 5743402,
          k: ['６４'],
          r: ['ロクヨン'],
          tr: [{ det: ['Nintendo 64 (col)'], type: ['product'] }],
          matchLen: 2,
        },
        // The following don't make sense but should be enough to force
        // us into multicol mode
        {
          id: 5743402,
          k: ['日本'],
          r: ['にっぽん'],
          tr: [{ type: ['surname'], det: ['Nippon'] }],
          matchLen: 2,
        },
        {
          id: 5743402,
          k: ['日本'],
          r: ['につぽん'],
          tr: [{ type: ['surname'], det: ['Nitsupon'] }],
          matchLen: 2,
        },
        {
          id: 5743402,
          k: ['日本'],
          r: ['にほん'],
          tr: [{ type: ['surname'], det: ['Nihon'] }],
          matchLen: 2,
        },
        {
          id: 5743402,
          k: ['日本'],
          r: ['ひのもと'],
          tr: [{ type: ['surname'], det: ['Hinomoto'] }],
          matchLen: 2,
        },
      ],
      matchLen: 2,
      more: false,
      fxData: {
        currency: 'EUR',
        rate: 0.006201584078062961,
        timestamp: 1732319104000,
      },
      preferredUnits: 'metric',
      copyState: { kind: 'inactive' },
      meta: { type: 'currency', value: 64040, matchLen: 7 },
    },
  ],
];

export default Object.fromEntries(
  TEST_ENTRIES.map((entry) => [
    entry[0],
    <NameTable {...entry[1]} key={entry[0]} />,
  ])
);
