allowBuilds:
  '@bugsnag/cli': true
  core-js: false
  edgedriver: false
  esbuild: true
  geckodriver: true
  spawn-sync: false
minimumReleaseAge: 1440 # 1 day
minimumReleaseAgeExclude:
  - '@birchill/*'
