allowBuilds:
  '@bugsnag/cli': true
  core-js: false
  edgedriver: false
  esbuild: true
  geckodriver: true
  spawn-sync: false
fullMetadata: true # needed for minimumReleaseAge to work reliably
minimumReleaseAge: 1440 # 1 day
minimumReleaseAgeExclude:
  - '@birchill/*'
  - react-cosmos-plugin-rspack
