name: 'Publish Firefox'
description: 'Publishes the add-on on AMO'
inputs:
  amo_jwt_iss:
    description: The JWT issuer (also refered to as the API key) from https://addons.mozilla.org/en-US/developers/addon/api/key/
    required: true
  amo_jwt_secret:
    description: The JWT secret from https://addons.mozilla.org/en-US/developers/addon/api/key/
    required: true
  addon_id:
    description: The numeric add-on ID, addon slug, or add-on GUID
    required: true
  release_id:
    description: The ID of the release to publish
    required: true
  release_notes:
    description: The release notes to use for the new version. If not set, the body of the release will be used.
  addon_asset_name:
    description: The last part of the name of the add-on asset within the release
    required: true
  source_asset_name:
    description: The last part of the name of the source asset within the release
runs:
  using: 'node16'
  main: 'index.js'
